### ISSUE TITLE
Modernize the Site CSS to create a new Palisadoes Foundation Standard

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/developer-docs#15]
**Is your feature request related to a problem? Please describe.**

The current site look and feel is not optimal. We need it to be more modern. The Hasura v2.0 documentation site has an attractive color scheme that matches our desired approach. 
- https://hasura.io/docs/3.0/index/

**Describe the solution you'd like**

1. Convert the CSS in this repo that's used for developer.palisadoes.org to match that of https://hasura.io/docs/3.0/index/
2. The reference CSS should be available here:
    - https://github.com/hasura/ddn-docs/tree/main
3. Also, we want to reduce the width of this slider to a width equal to that used by Hasura.
    ![image](https://github.com/user-attachments/assets/417e2136-17ef-4f3e-a741-bfda60084481)
4. We also want to enclose the site's home page welcome text in a card with rounded like this:
    ![image](https://github.com/user-attachments/assets/f071adbc-3b1c-42ac-991a-f5c1975fa9c7)

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- N/A

**Additional context**

- We plan to use the resulting layout for all Palisadoes Foundation Docusaurus based websites

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/developer-docs/issues/359

**Comment by hars-21** [comment]
Can I work on this?

**Comment by MohitMaulekhi** [comment]
Pls assign

**Comment by Krishnaidnani** [comment]
I have started working on this , can i continue to work ?

**Comment by bint-Eve** [comment]
sir i have solved this, can i raise PR ? will my PR be considered ?

**Comment by palisadoes** [comment]
> sir i have solved this, can i raise PR ? will my PR be considered ?

There will be another similar issue created soon

**Comment by bint-Eve** [comment]
ok sir !

**Comment by hars-21** [comment]
Sir would you like me to include refactoring the navbar and footer styles as well, or should I focus solely on the main content and sidebar?

**Comment by palisadoes** [comment]
> Sir would you like me to include refactoring the navbar and footer styles as well, or should I focus solely on the main content and sidebar?

Yes, refactor the NavBar too. I forgot to reference you.
