### ISSUE TITLE
Create a developer.palisadoes.org website

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/developer-docs#3]
**Is your feature request related to a problem? Please describe.**

1. This is a docusaurus repo that provides content for the https://developer.palisadoes.org/ website 
1. We need to create an attractive typescript based home page for future Palisadoes Developers that is different in design to talawa-docs. 
    1. The talawa-docs repository is a Docusaurus repo that provides conent for the https://docs.talawa.io/ website. 
3. This https://developer.palisadoes.org/  website will be the launchpad site for:
    1. All our project documentation
    2. All our internship documentation including GSoC and Calico

**Describe the solution you'd like**

1. We have adequate content in this repository. We just need to create a home page that welcomes new contributors to our community.
2. Use the https://docs.talawa.io/ site and its repository https://github.com/PalisadoesFoundation/talawa-docs as a guide on how this could be done
    1. There are more resources below
1. The design must be color blind friendly

We prefer an interesting, modern, professional design that will attract and retain new contributors

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- N/A

**Additional context**

Here are some examples of GitHub sites that have interesting themes. Links also include information on how to set up CSS files.

1. https://docusaurus.io/showcase
1. https://docusaurus.io/docs/next/styling-layout
1. https://docusaurus.io/docs/api/themes

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/developer-docs/issues/359

**Comment by VanshikaSabharwal** [comment]
Hey @palisadoes i would love to work on this issue

**Comment by palisadoes** [comment]
The design needs to be color blind friendly

**Comment by VanshikaSabharwal** [comment]
> The design needs to be color blind friendly

Yes @palisadoes I got it

**Comment by VanshikaSabharwal** [comment]
i am working on this issue

**Comment by VanshikaSabharwal** [comment]
I have raised PR  and i am working on this issue
